// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/types";
import type * as prismicClient from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Item in *Event → Filter*
 */
export interface EventDocumentDataFilterItem {
  /**
   * Filter field in *Event → Filter*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event.filter[].filter
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  filter: prismic.KeyTextField;

  /**
   * Color field in *Event → Filter*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: event.filter[].color
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  color: prismic.ColorField;
}

type EventDocumentDataSlicesSlice = ButtonsSlice;

/**
 * Content for Event documents
 */
interface EventDocumentData {
  /**
   * Title field in *Event*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Image field in *Event*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: event.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Date(s) field in *Event*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event.dates
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  dates: prismic.KeyTextField;

  /**
   * Date (for order) field in *Event*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: event.date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  date: prismic.DateField;

  /**
   * Time field in *Event*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event.time
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  time: prismic.KeyTextField;

  /**
   * Description field in *Event*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Filter field in *Event*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: event.filter[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  filter: prismic.GroupField<Simplify<EventDocumentDataFilterItem>>;

  /**
   * Button field in *Event*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: event.button
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Long description (Left) field in *Event*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event.long_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  long_description: prismic.RichTextField;

  /**
   * Long description (Right) field in *Event*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event.long_description2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  long_description2: prismic.RichTextField;

  /**
   * Slice Zone field in *Event*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: event.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<EventDocumentDataSlicesSlice> /**
   * Meta Title field in *Event*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: event.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Event*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: event.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Event*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: event.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Event document from Prismic
 *
 * - **API ID**: `event`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EventDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<EventDocumentData>, "event", Lang>;

type HomepageDocumentDataSlicesSlice = ButtonsSlice | HeroSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Title field in *Homepage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

/**
 * Item in *Navigation → Menu*
 */
export interface NavigationDocumentDataMenuItem {
  /**
   * Link field in *Navigation → Menu*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.menu[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Sublink field in *Navigation → Menu*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.menu[].sublink
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  sublink: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Content for Navigation documents
 */
interface NavigationDocumentData {
  /**
   * Menu field in *Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.menu[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  menu: prismic.GroupField<Simplify<NavigationDocumentDataMenuItem>>;

  /**
   * Footer field in *Navigation*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.footer
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  footer: prismic.RichTextField;
}

/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavigationDocumentData>,
    "navigation",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | ColumnsSlice
  | TeamItemSlice
  | NewsItemSlice
  | ButtonsSlice
  | HeroSlice
  | RichTextSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never> /**
   * Title SVG field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title_svg
   * - **Tab**: Title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  title_svg: prismic.KeyTextField;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

type ProgrammaDocumentDataSlicesSlice = never;

/**
 * Content for Programma documents
 */
interface ProgrammaDocumentData {
  /**
   * Title field in *Programma*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: programma.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Slice Zone field in *Programma*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: programma.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ProgrammaDocumentDataSlicesSlice> /**
   * Meta Title field in *Programma*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: programma.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Programma*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: programma.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Programma*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: programma.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never> /**
   * Title SVG field in *Programma*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: programma.title_svg
   * - **Tab**: Title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  title_svg: prismic.KeyTextField;
}

/**
 * Programma document from Prismic
 *
 * - **API ID**: `programma`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProgrammaDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProgrammaDocumentData>,
    "programma",
    Lang
  >;

export type AllDocumentTypes =
  | EventDocument
  | HomepageDocument
  | NavigationDocument
  | PageDocument
  | ProgrammaDocument;

/**
 * Primary content in *Buttons → Default → Primary*
 */
export interface ButtonsSliceDefaultPrimary {
  /**
   * Button field in *Buttons → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: buttons.default.primary.button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Default variation for Buttons Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ButtonsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ButtonsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Buttons*
 */
type ButtonsSliceVariation = ButtonsSliceDefault;

/**
 * Buttons Shared Slice
 *
 * - **API ID**: `buttons`
 * - **Description**: Buttons
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ButtonsSlice = prismic.SharedSlice<
  "buttons",
  ButtonsSliceVariation
>;

/**
 * Item in *Columns → Default → Primary → Columns*
 */
export interface ColumnsSliceDefaultPrimaryColumnsItem {
  /**
   * Text field in *Columns → Default → Primary → Columns*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: columns.default.primary.columns[].text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;
}

/**
 * Primary content in *Columns → Default → Primary*
 */
export interface ColumnsSliceDefaultPrimary {
  /**
   * Columns field in *Columns → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: columns.default.primary.columns[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  columns: prismic.GroupField<Simplify<ColumnsSliceDefaultPrimaryColumnsItem>>;
}

/**
 * Default variation for Columns Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ColumnsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ColumnsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Columns*
 */
type ColumnsSliceVariation = ColumnsSliceDefault;

/**
 * Columns Shared Slice
 *
 * - **API ID**: `columns`
 * - **Description**: Columns
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ColumnsSlice = prismic.SharedSlice<
  "columns",
  ColumnsSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Video field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.video
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  video: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * Hide Video field in *Hero → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: hero.default.primary.hide_video
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  hide_video: prismic.BooleanField;

  /**
   * Link field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Item in *NewsItem → Default → Primary → Item*
 */
export interface NewsItemSliceDefaultPrimaryItemItem {
  /**
   * Image field in *NewsItem → Default → Primary → Item*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: news_item.default.primary.item[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *NewsItem → Default → Primary → Item*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: news_item.default.primary.item[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *NewsItem → Default → Primary → Item*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: news_item.default.primary.item[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Button field in *NewsItem → Default → Primary → Item*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: news_item.default.primary.item[].button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Item in *NewsItem → Default → Primary → Upcoming*
 */
export interface NewsItemSliceDefaultPrimaryUpcomingItem {
  /**
   * Event field in *NewsItem → Default → Primary → Upcoming*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: news_item.default.primary.upcoming[].event
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  event: ContentRelationshipFieldWithData<
    [
      {
        id: "event";
        fields: ["title", "image", "date", "time", "description", "button"];
      },
    ]
  >;
}

/**
 * Item in *NewsItem → Default → Primary → Blog*
 */
export interface NewsItemSliceDefaultPrimaryBlogItem {
  /**
   * Blog Title field in *NewsItem → Default → Primary → Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: news_item.default.primary.blog[].blog_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  blog_title: prismic.KeyTextField;

  /**
   * Date field in *NewsItem → Default → Primary → Blog*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: news_item.default.primary.blog[].date
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  date: prismic.DateField;

  /**
   * Text field in *NewsItem → Default → Primary → Blog*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: news_item.default.primary.blog[].text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;
}

/**
 * Primary content in *NewsItem → Default → Primary*
 */
export interface NewsItemSliceDefaultPrimary {
  /**
   * Item field in *NewsItem → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: news_item.default.primary.item[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  item: prismic.GroupField<Simplify<NewsItemSliceDefaultPrimaryItemItem>>;

  /**
   * Upcoming field in *NewsItem → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: news_item.default.primary.upcoming[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  upcoming: prismic.GroupField<
    Simplify<NewsItemSliceDefaultPrimaryUpcomingItem>
  >;

  /**
   * Blog field in *NewsItem → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: news_item.default.primary.blog[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  blog: prismic.GroupField<Simplify<NewsItemSliceDefaultPrimaryBlogItem>>;
}

/**
 * Default variation for NewsItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NewsItemSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NewsItemSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *NewsItem*
 */
type NewsItemSliceVariation = NewsItemSliceDefault;

/**
 * NewsItem Shared Slice
 *
 * - **API ID**: `news_item`
 * - **Description**: NewsItem
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NewsItemSlice = prismic.SharedSlice<
  "news_item",
  NewsItemSliceVariation
>;

/**
 * Primary content in *RichText → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Content field in *RichText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum...
   * - **API ID Path**: rich_text.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;

  /**
   * Full Width field in *RichText → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: rich_text.default.primary.full_width
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  full_width: prismic.BooleanField;

  /**
   * Side Column field in *RichText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_text.default.primary.side_column
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  side_column: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

/**
 * Item in *TeamItem → Default → Primary → Item*
 */
export interface TeamItemSliceDefaultPrimaryItemItem {
  /**
   * Image field in *TeamItem → Default → Primary → Item*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: team_item.default.primary.item[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Name field in *TeamItem → Default → Primary → Item*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_item.default.primary.item[].name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Role field in *TeamItem → Default → Primary → Item*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_item.default.primary.item[].role
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  role: prismic.RichTextField;

  /**
   * Description field in *TeamItem → Default → Primary → Item*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_item.default.primary.item[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *TeamItem → Default → Primary*
 */
export interface TeamItemSliceDefaultPrimary {
  /**
   * Item field in *TeamItem → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: team_item.default.primary.item[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  item: prismic.GroupField<Simplify<TeamItemSliceDefaultPrimaryItemItem>>;
}

/**
 * Default variation for TeamItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TeamItemSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TeamItemSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TeamItem*
 */
type TeamItemSliceVariation = TeamItemSliceDefault;

/**
 * TeamItem Shared Slice
 *
 * - **API ID**: `team_item`
 * - **Description**: TeamItem
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TeamItemSlice = prismic.SharedSlice<
  "team_item",
  TeamItemSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismicClient.ClientConfig,
    ): prismicClient.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismicClient.WriteClientConfig,
    ): prismicClient.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismicClient.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      EventDocument,
      EventDocumentData,
      EventDocumentDataFilterItem,
      EventDocumentDataSlicesSlice,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      NavigationDocument,
      NavigationDocumentData,
      NavigationDocumentDataMenuItem,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      ProgrammaDocument,
      ProgrammaDocumentData,
      ProgrammaDocumentDataSlicesSlice,
      AllDocumentTypes,
      ButtonsSlice,
      ButtonsSliceDefaultPrimary,
      ButtonsSliceVariation,
      ButtonsSliceDefault,
      ColumnsSlice,
      ColumnsSliceDefaultPrimaryColumnsItem,
      ColumnsSliceDefaultPrimary,
      ColumnsSliceVariation,
      ColumnsSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      NewsItemSlice,
      NewsItemSliceDefaultPrimaryItemItem,
      NewsItemSliceDefaultPrimaryUpcomingItem,
      NewsItemSliceDefaultPrimaryBlogItem,
      NewsItemSliceDefaultPrimary,
      NewsItemSliceVariation,
      NewsItemSliceDefault,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
      TeamItemSlice,
      TeamItemSliceDefaultPrimaryItemItem,
      TeamItemSliceDefaultPrimary,
      TeamItemSliceVariation,
      TeamItemSliceDefault,
    };
  }
}
