// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  buttons: dynamic(() => import("./Buttons")),
  columns: dynamic(() => import("./Columns")),
  hero: dynamic(() => import("./Hero")),
  news_item: dynamic(() => import("./NewsItem")),
  rich_text: dynamic(() => import("./RichText")),
  team_item: dynamic(() => import("./TeamItem")),
};
