// Code generated by Slice Machine. DO NOT EDIT.

import Buttons from './Buttons';
import Hero from './Hero';
import RichText from './RichText';
import NewsItem from './NewsItem';
import TeamItem from './TeamItem';
import EventItem from './EventItem';
import Columns from './Columns'


export {
	Buttons,
	Hero,
	RichText,
	NewsItem,
	TeamItem,
	EventItem,
	Columns
};

export const components = {
	buttons: Buttons,
	hero: Hero,
	rich_text: RichText,
	news_item: NewsItem,
	team_item: TeamItem,
	event_item: EventItem,
	columns: Columns
};
